export const allowedTopics = {
    LeetCode: [
      "interview",
      "questions",
      "arrays",
      "strings",
      "linked lists",
      "stacks",
      "queues",
      "hash tables",
      "trees",
      "binary trees",
      "binary search trees",
      "heaps",
      "graphs",
      "depth-first search",
      "breadth-first search",
      "dynamic programming",
      "recursion",
      "backtracking",
      "sorting",
      "searching",
      "greedy algorithms",
      "bit manipulation",
      "math",
      "two pointers",
      "sliding window",
      "union find",
      "trie",
      "segment tree",
      "binary indexed tree",
      "intervals",
      "matrix",
      "topological sort",
      "graph traversal",
      "shortest path",
      "minimum spanning tree",
      "divide and conquer",
      "string matching",
      "combinatorics",
      "geometry",
      "probability",
      "game theory",
      "design",
      "concurrency",
    ],
    DBMS: [
      "database",
      "SQL",
      "NoSQL",
      "ACID properties",
      "ER model",
      "normalization",
      "denormalization",
      "indexes",
      "views",
      "stored procedures",
      "triggers",
      "transactions",
      "joins",
      "subqueries",
      "aggregate functions",
      "relational algebra",
      "functional dependencies",
      "BCNF",
      "1NF",
      "2NF",
      "3NF",
      "4NF",
      "5NF",
      "Big Data",
      "OLAP",
      "OLTP",
      "data warehousing",
      "sharding",
      "replication",
      "partitioning",
      "concurrency control",
      "deadlock",
      "RAID",
      "CAP theorem",
      "MongoDB",
      "Redis",
      "Cassandra",
      "Elasticsearch",
      "Graph databases",
    ],
    CPP: [
      "c++",
      "stl",
      "pointers",
      "oop",
      "classes",
      "dynamic memory",
      "syntax",
      "inheritance",
      "polymorphism",
      "maps",
      "vectors",
      "sets",
      "queues",
      "memory management",
      "file handling",
      "templates",
      "lambda expressions",
      "functional programming",
      "operator overloading",
      "exception handling",
      "multithreading",
      "graphs",
      "trees",
      "sorting",
      "searching",
      "dynamic programming",
      "recursion",
      "bit manipulation",
      "design patterns",
    ],
    JavaScript: [
      "syntax",
      "variables",
      "data types",
      "functions",
      "ES6",
      "arrow functions",
      "closures",
      "hoisting",
      "DOM manipulation",
      "event handling",
      "callbacks",
      "promises",
      "async/await",
      "fetch API",
      "localStorage",
      "sessionStorage",
      "cookies",
      "modules",
      "spread/rest operators",
      "destructuring",
      "Map",
      "Set",
      "WeakMap",
      "WeakSet",
      "higher-order functions",
      "functional programming",
      "error handling",
      "prototypes",
      "this keyword",
      "bind/call/apply",
      "currying",
      "memoization",
      "WebSockets",
      "Service Workers",
      "WebRTC",
      "GraphQL",
      "REST APIs",
      "JSON",
      "regex",
      "performance optimization",
    ],
    Java: [
      "syntax",
      "OOP",
      "classes",
      "objects",
      "inheritance",
      "polymorphism",
      "abstraction",
      "encapsulation",
      "constructors",
      "interfaces",
      "exception handling",
      "multithreading",
      "JVM",
      "JRE",
      "JDK",
      "Garbage Collection",
      "Lambda Expressions",
      "Streams API",
      "Collections Framework",
      "ArrayList",
      "LinkedList",
      "HashMap",
      "TreeMap",
      "HashSet",
      "PriorityQueue",
      "Sorting",
      "Searching",
      "Recursion",
      "Functional Programming",
      "File Handling",
      "Database Connectivity",
      "JDBC",
      "Spring Boot",
      "Hibernate",
      "Servlets",
      "JSP",
      "REST APIs",
      "Design Patterns",
    ],
    ComputerNetworks: [
      "networking basics",
      "OSI model",
      "TCP/IP model",
      "IP addressing",
      "IPv4",
      "IPv6",
      "subnetting",
      "CIDR",
      "MAC addressing",
      "ARP",
      "DNS",
      "DHCP",
      "NAT",
      "routing",
      "switching",
      "firewalls",
      "load balancing",
      "proxy servers",
      "HTTP",
      "HTTPS",
      "FTP",
      "SMTP",
      "POP3",
      "IMAP",
      "SNMP",
      "ICMP",
      "VPN",
      "LAN",
      "WAN",
      "MAN",
      "PAN",
      "VLAN",
      "wireless networks",
      "Wi-Fi",
      "Bluetooth",
      "mobile networks",
      "4G",
      "5G",
      "network security",
      "encryption",
      "hashing",
      "TLS",
      "SSL",
      "SSH",
      "firewalls",
      "IDS",
      "IPS",
      "MITM attack",
      "DDoS attack",
      "packet sniffing",
      "port scanning",
      "network topologies",
      "star topology",
      "bus topology",
      "ring topology",
      "hybrid topology",
      "peer-to-peer networks",
      "client-server model",
      "CDN",
      "cloud networking",
      "edge computing",
      "SDN (Software-Defined Networking)",
      "IoT networking",
      "network protocols",
      "data link layer",
      "transport layer",
      "network layer",
      "application layer",
      "network congestion control",
      "troubleshooting",
      "Network Performance & Troubleshooting",
    ],
    React: [
      "components",
      "JSX",
      "props",
      "state",
      "lifecycle methods",
      "hooks",
      "useState",
      "useEffect",
      "useContext",
      "useReducer",
      "useMemo",
      "useCallback",
      "custom hooks",
      "context API",
      "react router",
      "redux",
      "redux toolkit",
      "react-redux",
      "performance optimization",
      "react testing library",
      "enzyme",
      "SSR",
      "hydration",
      "react native",
      "next.js",
      "gatsby",
      "styled-components",
      "emotion",
      "material-ui",
      "ant design",
      "tailwind CSS",
      "framer motion",
      "react spring",
    ],
    NodeJS: [
      "event loop",
      "non-blocking I/O",
      "asynchronous programming",
      "callbacks",
      "promises",
      "async/await",
      "modules",
      "npm",
      "express",
      "koa",
      "hapi",
      "nest.js",
      "REST APIs",
      "GraphQL",
      "websockets",
      "socket.io",
      "file system",
      "streams",
      "buffers",
      "child processes",
      "cluster",
      "middleware",
      "authentication",
      "authorization",
      "JWT",
      "passport.js",
      "session management",
      "error handling",
      "logging",
      "debugging",
      "testing",
      "mocha",
      "chai",
      "jest",
      "supertest",
      "database connectivity",
      "mongoose",
      "sequelize",
      "knex.js",
      "redis",
      "caching",
      "performance optimization",
      "security",
      "rate limiting",
      "helmet",
      "cors",
      "dotenv",
    ],
    NextJS: [
      "pages",
      "components",
      "routing",
      "API routes",
      "getStaticProps",
      "getServerSideProps",
      "getStaticPaths",
      "dynamic routing",
      "SSR",
      "SSG",
      "ISR",
      "data fetching",
      "API integration",
      "middleware",
      "custom server",
      "environment variables",
      "styled-jsx",
      "CSS modules",
      "Sass",
      "tailwind CSS",
      "performance optimization",
      "image optimization",
      "static file serving",
      "deployment",
      "Vercel",
      "Netlify",
      "AWS",
      "Azure",
      "Firebase",
      "authentication",
      "authorization",
      "next-auth",
      "security",
      "testing",
      "jest",
      "react testing library",
    ],
    Backend: [
      "architecture",
      "REST APIs",
      "GraphQL",
      "authentication",
      "authorization",
      "JWT",
      "OAuth",
      "session management",
      "database design",
      "SQL",
      "NoSQL",
      "ORM",
      "ODM",
      "caching",
      "redis",
      "memcached",
      "message queues",
      "rabbitMQ",
      "kafka",
      "microservices",
      "serverless",
      "AWS Lambda",
      "Azure Functions",
      "Google Cloud Functions",
      "containerization",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Jenkins",
      "GitHub Actions",
      "GitLab CI",
      "monitoring",
      "logging",
      "performance optimization",
      "security",
      "rate limiting",
      "API gateways",
      "reverse proxies",
      "Nginx",
      "HAProxy",
      "load balancing",
      "scalability",
      "fault tolerance",
      "disaster recovery",
    ],
    Frontend: [
      "HTML",
      "CSS",
      "JavaScript",
      "responsive design",
      "flexbox",
      "grid",
      "media queries",
      "accessibility",
      "ARIA",
      "semantic HTML",
      "performance optimization",
      "webpack",
      "babel",
      "parcel",
      "vite",
      "npm",
      "yarn",
      "pnpm",
      "version control",
      "git",
      "GitHub",
      "GitLab",
      "Bitbucket",
      "testing",
      "jest",
      "react testing library",
      "cypress",
      "storybook",
      "design systems",
      "material design",
      "ant design",
      "bootstrap",
      "tailwind CSS",
      "styled-components",
      "emotion",
      "framer motion",
      "react spring",
      "state management",
      "redux",
      "redux toolkit",
      "mobx",
      "recoil",
      "context API",
      "hooks",
      "SSR",
      "hydration",
      "next.js",
      "gatsby",
      "static site generation",
      "progressive web apps",
      "service workers",
      "websockets",
      "webRTC",
      "GraphQL",
      "Apollo",
      "relay",
    ],
    SQL: [
      "database design",
      "normalization",
      "denormalization",
      "ACID properties",
      "transactions",
      "indexes",
      "views",
      "stored procedures",
      "triggers",
      "joins",
      "subqueries",
      "aggregate functions",
      "window functions",
      "CTEs",
      "relational algebra",
      "functional dependencies",
      "BCNF",
      "1NF",
      "2NF",
      "3NF",
      "4NF",
      "5NF",
      "SQL injection",
      "performance optimization",
      "query optimization",
      "database security",
      "backup and recovery",
      "replication",
      "sharding",
      "partitioning",
      "data warehousing",
      "OLAP",
      "OLTP",
      "Big Data",
      "NoSQL",
      "MongoDB",
      "Redis",
      "Cassandra",
      "Elasticsearch",
      "Graph databases",
    ],
  };